# Generated by Django 3.1 on 2021-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
