# Generated by Django 3.1 on 2021-07-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_auto_20210730_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
