# Generated by Django 3.1 on 2021-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=700)),
                ('image', models.ImageField(upload_to='client/')),
            ],
        ),
    ]
